---
- name: generate PreprovisionedInventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: generate template
      template:
        src: templates/PreprovisionedInventory.yml.j2
        dest: PreprovisionedInventory.yml

- name: wait for nodes
  hosts: master,worker
  gather_facts: false
  tasks:
    -  wait_for_connection:
        timeout: 600

- name: create dir for local-path-provisioner
  hosts: master,worker
  gather_facts: no
  become: true
  tasks:
    - file: 
        path: /mnt/disks
        state: directory